/**
 * VCD (Value Change Dump) Parser
 * Parses VCD files generated by iverilog/verilator into
 * the signal data format used by RTL Bench waveform viewer.
 */

/**
 * Parse a VCD string into signal data.
 * @param {string} vcdText — raw VCD file content
 * @returns {{ signals: Array, totalTime: number }}
 */
function parseVCD(vcdText) {
  const lines = vcdText.split('\n');

  // --- Phase 1: Parse header and build symbol → signal map ---
  const symbolMap = {}; // symbol char → { name, width, type }
  const scopeStack = [];
  let timescaleUnit = 1; // in nanoseconds
  let i = 0;

  while (i < lines.length) {
    const line = lines[i].trim();

    if (line.startsWith('$timescale')) {
      // Collect until $end
      let ts = '';
      while (i < lines.length && !lines[i].includes('$end')) {
        ts += lines[i] + ' ';
        i++;
      }
      ts += lines[i]; // include the $end line
      const match = ts.match(/(\d+)\s*(ps|ns|us|ms|s)/i);
      if (match) {
        const val = parseInt(match[1]);
        const unit = match[2].toLowerCase();
        const factors = { ps: 0.001, ns: 1, us: 1000, ms: 1000000, s: 1e9 };
        timescaleUnit = val * (factors[unit] || 1);
      }
    } else if (line.startsWith('$scope')) {
      const parts = line.split(/\s+/);
      if (parts.length >= 3) scopeStack.push(parts[2]);
    } else if (line.startsWith('$upscope')) {
      scopeStack.pop();
    } else if (line.startsWith('$var')) {
      // $var wire 1 ! clk $end  OR  $var wire 4 # count [3:0] $end
      const parts = line.replace('$var', '').replace('$end', '').trim().split(/\s+/);
      if (parts.length >= 4) {
        const varType = parts[0]; // wire, reg, etc.
        const width = parseInt(parts[1]);
        const symbol = parts[2];
        let name = parts[3];
        // Handle bit range like [3:0]
        if (parts.length >= 5 && parts[4].startsWith('[')) {
          name += parts[4];
        }
        // Prepend scope if nested
        const fullName = scopeStack.length > 0
          ? scopeStack[scopeStack.length - 1] + '.' + name
          : name;

        symbolMap[symbol] = {
          name: fullName,
          width,
          type: width > 1 ? 'bus' : 'bit',
          data: [],
          lastValue: width > 1 ? 0 : 0,
        };
      }
    } else if (line === '$enddefinitions $end' || line.startsWith('$enddefinitions')) {
      i++;
      break; // Move to simulation section
    }
    i++;
  }

  // --- Phase 2: Parse simulation commands ---
  let currentTime = 0;
  let maxTime = 0;

  // Assign colors based on signal index
  const COLORS = [
    '#58A6FF', '#FF7B72', '#7EE787', '#FFA657',
    '#D2A8FF', '#79C0FF', '#56D364', '#E3B341',
    '#F778BA', '#A5D6FF',
  ];
  const symbolList = Object.keys(symbolMap);
  symbolList.forEach((sym, idx) => {
    symbolMap[sym].color = COLORS[idx % COLORS.length];
  });

  while (i < lines.length) {
    const line = lines[i].trim();
    i++;
    if (!line || line.startsWith('$comment') || line.startsWith('$dumpvars') || line.startsWith('$end')) continue;

    // Timestamp
    if (line.startsWith('#')) {
      currentTime = parseInt(line.substring(1));
      if (currentTime > maxTime) maxTime = currentTime;
      continue;
    }

    // Scalar value change: 0! 1# xA etc.
    if (/^[01xXzZ]/.test(line) && line.length >= 2) {
      const val = line[0];
      const sym = line.substring(1);
      if (symbolMap[sym]) {
        const numVal = (val === '1') ? 1 : 0;
        const sig = symbolMap[sym];
        // Only push if value changed or first entry
        if (sig.data.length === 0 || sig.data[sig.data.length - 1].value !== numVal) {
          sig.data.push({ time: currentTime, value: numVal });
          sig.lastValue = numVal;
        }
      }
      continue;
    }

    // Vector value change: b0000 # OR b1111 A
    if (/^b/i.test(line)) {
      const parts = line.split(/\s+/);
      if (parts.length >= 2) {
        const binStr = parts[0].substring(1); // remove 'b'
        const sym = parts[1];
        if (symbolMap[sym]) {
          // Convert binary string to number (handle x/z as 0)
          const cleanBin = binStr.replace(/x/gi, '0').replace(/z/gi, '0');
          const numVal = parseInt(cleanBin, 2) || 0;
          const sig = symbolMap[sym];
          if (sig.data.length === 0 || sig.data[sig.data.length - 1].value !== numVal) {
            sig.data.push({ time: currentTime, value: numVal });
            sig.lastValue = numVal;
          }
        }
      }
      continue;
    }
  }

  // --- Phase 3: Finalize signal list ---
  // Filter out signals with no data or scope-internal signals we don't want
  // Build the final signals array, ensuring each signal has a terminal point at maxTime
  const signals = symbolList
    .map(sym => symbolMap[sym])
    .filter(sig => sig.data.length > 0)
    .map(sig => {
      // Add terminal point at maxTime if not already there
      const last = sig.data[sig.data.length - 1];
      if (last && last.time < maxTime) {
        sig.data.push({ time: maxTime, value: last.value });
      }
      return {
        name: sig.name,
        type: sig.type,
        width: sig.width,
        data: sig.data,
        color: sig.color,
      };
    });

  // Convert time to nanoseconds if timescale is not 1ns
  const needsScale = timescaleUnit !== 1;
  if (needsScale) {
    signals.forEach(sig => {
      sig.data = sig.data.map(pt => ({ time: pt.time * timescaleUnit, value: pt.value }));
    });
    maxTime = maxTime * timescaleUnit;
  }

  return { signals, totalTime: maxTime || 100 };
}

module.exports = { parseVCD };
